### ISSUE TITLE
[BUG] BO2 Vetos not working

### ISSUE THREAD

**Issue by kubo6472** [PhlexPlexico/G5API#130] opened 2021-10-17 09:29 UTC
**Describe the bug**
Vetos are not being displayed

**To Reproduce**
Run a match
Tested with BO2

**Expected behavior**
Vetos and Veto sides (#100) will be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/26146502/137621116-d67a714a-e30f-4c82-8ef7-f5d2604135b7.png)

**Additional context**
From #128

**Comment by kubo6472** [comment] 2021-10-17 15:46
Yep, console is full of logs. Going with a quick BO1 instead now and will let you know if anything pops up

**Comment by kubo6472** [comment] 2021-10-17 20:21
BO1: 
![image](https://user-images.githubusercontent.com/26146502/137643573-4cf85312-0a0d-4f00-bbfd-214ced38cf96.png)

**Comment by PhlexPlexico** [comment] 2021-10-17 20:23
That seems to be an error with get5 then for vetoes. What's your config/logs/etc?

**Comment by kubo6472** [comment] 2021-10-17 20:25
![image](https://user-images.githubusercontent.com/26146502/137643629-33b94bb7-5cc3-4769-b7cd-c1aa53da8c6a.png)
BO3 started happening since get5ws update
![image](https://user-images.githubusercontent.com/26146502/137643649-a38b78d2-f290-499f-a675-c466d294f6f0.png)
G5API seems to tell the true, so moment, I am getting the logs.
https://hastebin.com/ojixiriyin.yaml

**Comment by kubo6472** [comment] 2021-10-17 20:46
I see
```
 if (req != null && (team1MapScore == team2MapScore || !isCancelled)) {
    seriesRes.SetString("key", g_APIKey);
    seriesRes.SetString("winner", winnerString);
    seriesRes.SetInt("team1score", team1MapScore);
    seriesRes.SetInt("team2score", team2MapScore);
    seriesRes.SetInt("forfeit", forfeit);
    req.Post(seriesRes, RequestCallback);
  }
```
this goes thru even on 0:0 therefore every match is now considered to be a BO2 @PhlexPlexico

**Comment by kubo6472** [comment] 2021-10-17 20:48
> 
> 
> I see
> 
> ```
>  if (req != null && (team1MapScore == team2MapScore || !isCancelled)) {
>     seriesRes.SetString("key", g_APIKey);
>     seriesRes.SetString("winner", winnerString);
>     seriesRes.SetInt("team1score", team1MapScore);
>     seriesRes.SetInt("team2score", team2MapScore);
>     seriesRes.SetInt("forfeit", forfeit);
>     req.Post(seriesRes, RequestCallback);
>   }
> ```
> 
> this goes thru even on 0:0 therefore every match is now considered to be a BO2 @PhlexPlexico

therefore adding a check if that map score is !== 0 will be sufficient enough

**Comment by kubo6472** [comment] 2021-10-17 21:41
> It's also looking like it's working according to your third match? https://cs.jakubdobos.eu/api/vetoes/3

https://cs.jakubdobos.eu/match/3 so where do you think the issue lies then? and should I open the new issue for the veto being BO2 all the time, as seen in the screenshots

**Comment by PhlexPlexico** [comment] 2021-10-17 21:43
Well I still haven't seen any debug logs from the game server either, so I can't tell if for some reason the BO2 flag is still set, or what it is trying to grab veto information from. But if it's only happening on the game server, I would guess it may be a get5 issue more so than an API issue. Have you tried just doing a BO1 on a clean server that has not had a BO2 setup? Have you made any changes to your get5 configs?

**Comment by PhlexPlexico** [comment] 2021-10-17 21:51
And looking at the web panel, there was a match yesterday on the public played that was a BO1 and that was played properly - https://phlex.avidgamers.me/api/matches/706

In your error it's saying team_name is not defined. Do you have the veto update table in your database? How about the veto table?

**Comment by kubo6472** [comment] 2021-10-17 22:36
> In your error it's saying team_name is not defined. Do you have the veto update table in your database? How about the veto table?

All tables are present.
> As for your config and debug info sent, it was a BO2 match with g_BO2Match set to 1, so where is the issue there, it seems like the bans/pick process was correct from the log files you provided.

Well I created a BO1 & a BO3 respectively
> E: as an aside - I've updated the logic with the front end to display vetoes as well. So please update/rebuild the front end to see the vetoes as well.

Will do, if that fixes it, then vi von 🤣

**Comment by PhlexPlexico** [comment] 2021-10-17 22:46
Well, I mean if the vetoes in game aren't being set properly (i.e. still two picks per a BO1) then that's a get5 bug, since none of my stuff interacts with the game. 

Also according to the files provided, one match was definitely a BO2. Both the API and get5 confirm that.

https://hastebin.com/gupojodozi.yaml
https://cs.jakubdobos.eu/api/matches/3

**Comment by kubo6472** [comment] 2021-10-17 22:53
![image](https://user-images.githubusercontent.com/26146502/137647810-9af1adb4-96df-4572-a07b-9b098ad64f52.png)
thank you for the g5v update and also for all the stuff. I got to find a way how to fix this then.
https://cs.jakubdobos.eu/api/matches/3 BO1, had BO2 banning
https://cs.jakubdobos.eu/api/matches/4 BO3, had BO2 banning

**Comment by PhlexPlexico** [comment] 2021-10-17 23:23
As an aside @kubo6472 - if you need to locate your log files for PM2 they are most definitely located in `/root/.pm2/logs`, I was able to confirm.

Thanks!

**Comment by PhlexPlexico** [comment] 2021-10-18 05:38
Also, since this is a bug in get5 itself, I'm going to mark this as `wontfix` and close. Please make sure you create the issue in get5 with steps on how to reproduce. I believe it should be an easy enough fix after looking through some of the source and just setting `g_BO2Match` to 0/false when a series is cancelled or finished. I think, at least, I didn't look too much into it.

Thanks!

**Closed by PhlexPlexico** 2021-10-18 05:38 UTC
Labels: pending feedback, not reproducible

**Comment by kubo6472** [comment] 2021-10-18 07:10
Thanks for everything. Will do asap.
