### ISSUE TITLE
[BUG] Empty request body on linux web server

### ISSUE THREAD

**Issue by martitis** [PhlexPlexico/G5API#183] opened 2022-04-07 17:38 UTC
**Describe the bug**
Created fresh install on ubuntu web server and when stats are reported to web server I'm getting incorrect API key message on game server, although API key in database and on game server are the same.  When tried to capture packets with tcpdump on web server packet looks alright: 
![image](https://user-images.githubusercontent.com/22919949/162254615-32215b31-e9b5-4a95-86c5-430a63142dca.png)
But when printing req.body on web server I'm getting empty body response and error message on game server:
![image](https://user-images.githubusercontent.com/22919949/162256344-53e43ce1-55f5-4ffe-96cf-40bc66dadf51.png)
![image](https://user-images.githubusercontent.com/22919949/162263143-94670576-70cd-4d7b-8a63-73540390e08c.png)
![image](https://user-images.githubusercontent.com/22919949/162262151-bacd6779-310c-4bc6-a875-f21f144bd97a.png)

My configs:
production.json
```
{
  "server": {
    "port": 3301,
    "hostname": "https://test.ddns.net",
    "dbKey": "dbkey",
    "steamAPIKey": "key",
    "sharedSecret": "secret",
    "clientHome": "https://test.ddns.net",
    "useRedis": true,
    "apiURL": "https://test.ddns.net/api",
    "uploadDemos": true
  },
  "production": {
    "driver": "mysql",
    "user": "get5_user",
    "password": "password",
    "database": "get5",
    "multipleStatements": true,
    "flags": { "ENV": "MYSQL_FLAGS" },
    "host": "127.0.0.1",
    "port": 3306,
    "connectionLimit": 15,
    "redisHost": "localhost",
    "redisPort": 6379,
    "redisTTL": 86400,
    "redisPass": "password"
  },
  "admins": {
    "steam_ids": "id"
  },
  "super_admins": {
    "steam_ids": "id"
  }
}
```

/etc/nginx/sites-available/G5V
```
server {

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        # This is where the build for G5V resides, update this to wherever you need.
        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        # Change this to whichever hostname you have, such as get5.phlexplexi.co
        server_name test.ddns.net;

        # This is the main block that was added. Currently the API runs on port 3301. You may adjust to what you need it to if you changed ports in the config.
        location /api/ {
                proxy_pass http://192.168.0.175:3301/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
        }

        # IF YOU'RE USING THE DOCKER IMAGE, THIS WILL HAVE TO BE UPDATED IN THE DOCKER IMAGE ITSELF. Do not put this on your reverse proxy.
        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri /index.html;
        }


        # pass PHP scripts to FastCGI server
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php-fpm (or other unix sockets):
        #       fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        #       # With php-cgi (or other tcp sockets):
        #       fastcgi_pass 127.0.0.1:9000;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/test.ddns.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/test.ddns.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = test.ddns.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        listen 80 default_server;
        listen [::]:80 default_server;
        server_name test.ddns.net;
    return 404; # managed by Certbot


}
```

**Desktop :**
 - OS: Windows 10
 - Browser brave (chromium)
 - Version 1.37.111

**Server info**
 - OS: Ubuntu (Both WEB and CSGO)
 - Version Ubuntu 20.04.1 LTS
 - NodeJS version v14.18.1

P.S: Seen similar problem registered on G5WS project, but it were solved on windows server by using https, but I'm using linux server and tried using http and https but no luck.  
Also I tried to add my server to your demo website phlex.avidgamers.me and there everything works fine and stats are being reported correctly.  
Sorry for a bit messy report, but I tried to provide as much information as I can.

**Comment by PhlexPlexico** [comment] 2022-04-07 18:45
Hey! Thanks for all the info, it definitely helps with debugging here. A few questions I suppose:

1) Is that G5WS plugin the release from October? Would you mind trying to use the nightly release that had one small bug fix to it? [here](https://github.com/PhlexPlexico/G5WS/releases/tag/Nightly-d43b0c)
2) How are you outputting the `req.body` call, usually if you're calling just `console.log(req);` it shows it as `[Object object]`, so I'm not sure why it would be outputting that... 

I would think there may be a potential firewall/redirect issue maybe going on with the webserver? Are you using iptables or UFW on the Ubuntu system, and do you have access externally to your web panel as well?

Thanks!

**Comment by martitis** [comment] 2022-04-09 19:36
Thanks for your fast reply,
Just tried with this plugin version, same error occurs  
![image](https://user-images.githubusercontent.com/22919949/162589128-2a750606-fa9b-43b6-a8e3-32e5c9f524a3.png)
I'm accessing web panel externally and have UFW disabled, but server is behind NAT, also tried setting up server locally, but that doesn't helped.
For the 2nd point I'll try to parse somehow that req.body

**Comment by PhlexPlexico** [comment] 2022-04-09 20:50
Hmmm yeah I'm not too sure, but I think this may have something to do with a network configuration gone awry if it's working on the public panel... Sorry, but I don't think there is much else I can help with if the same game servers are working. It may have something to do with NAT, but I can't guarantee that either.

**Comment by martitis** [comment] 2022-04-10 13:33
Okay I think I might be using some bad dependencies or something, because I just setup web panel and csgo on one server and still getting error:  
![image](https://user-images.githubusercontent.com/22919949/162619995-f1f9ff8c-aabf-49bb-97d5-2337d5c12146.png)  
Adding some information:  
![image](https://user-images.githubusercontent.com/22919949/162620365-e6e3cb40-6b4c-4b09-b4b2-5b65387dd224.png)  
I'm currently cloned most recent version of repository,  maybe I'm using wrong version of something or something is incompatible?

**Comment by PhlexPlexico** [comment] 2022-04-10 15:54
I'm surprised node didn't tell at you. I believe the node version is out of date. You have 14.17.5 and the earliest version you require is here:

https://github.com/PhlexPlexico/G5API/blob/91982bbcb314a07268ddab722199a189d16b8aa1/package.json#L23

Try upgrading node (I use nvm personally to manage versions) and try again :)

**Comment by martitis** [comment] 2022-04-10 16:34
I switched my node to v14.18.1 and updated run yarn, but I'm still getting incorrect API key message, maybe you could post your demo server details (OS version, node version, yarn version, any other steps done that are not mentioned in setup instructions that are in wiki)?

**Comment by PhlexPlexico** [comment] 2022-04-10 16:49
Sure thing, lemme grab my public server. I have another instance running on Docker on a Pi too that seems to be working as intended. But anyways, here's the info for the public instance :)

Ubuntu 20.04
Nvm/node 14.18.1
Nginx 1.18
Yarn 1.22.18

Also, what release of Rest In PAWN are you using? Would you mind trying to just use the release 1.3.0? See if that works? Or just release 1.3.1? There is an issue in that repo that also has the debug statements, you could try using that and see what is getting sent over. 

As for the nginx conf, there should be a basic one in the repo here that the Docker container uses, so you may be able to reference that, too. But it's looking correct to me.

**Comment by martitis** [comment] 2022-04-10 18:27
Okay, just tested docker setup, here everything works fine, I'll try to troubleshoot my issue using docker

**Comment by PhlexPlexico** [comment] 2022-04-10 19:06
So since docker uses Caddy instead of nginx, I would maybe check the configs again. Very odd that the web server isn't requesting everything properly. Could it be the headers being sent and maybe the post body not redirecting to `/api` properly? A good way to test this is to open up port 3301 and use that as your apiURL... I think that will allow a direct connection to the node server :)

**Comment by PhlexPlexico** [comment] 2022-04-18 16:43
Hey @martitis, any updates on this? If not, I will close this ticket in 4 days.

Thanks!

**Comment by PhlexPlexico** [comment] 2022-04-24 19:54
Hey @martitis,

Since this is working on the docker container, I'm going to go ahead and close this. There may be an issue with he NGINX setup or the way it's interpreting the data, but I don't think this is the place to solve it. If you'd like, feel free to create a discussion and we can continue to investigate :)

Thanks!

**Closed by PhlexPlexico** 2022-04-24 19:54 UTC
Labels: pending feedback
